### ISSUE TITLE
Cannot download data, error or date

### ISSUE THREAD

**Issue by fhoubie** [olivierhagolle/peps_download#1]
Hi, I'm trying to download data using 

$ ./peps_download.py -l 'Chypre' -a peps.txt -d 2016-01-01 -f 2016-04-10
curl -k -o search.json https://peps.cnes.fr/resto/api/collections/S2/search.json?q=Chypre\&startDate=2016-01-01\&completionDate=2016-04-10\&maxRecords=500
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1345  100  1345    0     0   2971      0 --:--:-- --:--:-- --:--:--  3320
Not product matches the criteria

Executing the HTTP GET, I receive

{
ErrorMessage: "Value for "startDate" must follow the pattern ^[0-9]{4}-[0-9]{2}-[0-9]{2}(T[0-9]{2}:[0-9]{2}:[0-9]{2}(.[0-9]+)?(|Z|[+-][0-9]{2}:[0-9]{2}))?$",
ErrorCode: 400
}

Has something changed in the rocket service ?

Thanks

Frédéric

**Comment by olivierhagolle** [comment]
Hi Frederic, 
Maybe Chypre is not well recognised in the database of PEPS. I found a large number of products providing the coordinates of Nicosie  :  
`./peps_download.py -a hagolle.txt -d 2016-01-01 --lat 35.167 --lon 33.4`

Regarding the second issue, when you copy the URL from wget command line to a browser, you have to remove the backslashes that protect special characters like "&".

Best ragrds,
Olivier

**Comment by fhoubie** [comment]
Hi Olivier, I've checked with Jerome Gasperi and I have to use the ISO8601
Time format (with time and not date only). Chypre was not recognized by
Cyprus was.

Thanks

Frédéric

2016-04-09 8:05 GMT+02:00 Olivier Hagolle notifications@github.com:
