### ISSUE TITLE
Sentinel-1 download provide 0KO zip file (probably files on tape)

### ISSUE THREAD

**Issue by clardeux** [olivierhagolle/peps_download#12]
Hello,

after running the tool over French guyana to download data with these settings (end of issue), among the 203 files found in the script, only 137 was well downloaded. Other one are well in .zip but with a size equal to 0 KO. I don't control all of these files but some of that are on tape. May be it's the problem.

However, after the download, I delete the wrong files and run again the script without changing anything in order to complete the download and it's seems working well (not yet finished)

I use a xubuntu over OVH server.

Best regards

Example of one file that was not well downloaded:
S1B_IW_GRDH_1SDV_20170823T214212_20170823T214241_007073_00C75F_E440.zip
S1B_IW_GRDH_1SDV_20170730T214239_20170730T214308_006723_00BD39_5883.zip
S1A_IW_GRDH_1SDV_20170829T214323_20170829T214348_018144_01E7AE_17C8.zip
S1B_IW_GRDH_1SDV_20170811T214211_20170811T214240_006898_00C24E_21DA.zip
S1A_IW_GRDH_1SDV_20171004T214324_20171004T214349_018669_01F7D5_C9F9.zip
S1A_IW_GRDH_1SDV_20170805T214347_20170805T214412_017794_01DD18_B2BC.zip
S1A_IW_GRDH_1SDV_20171109T214255_20171109T214324_019194_0207E6_9D21.zip
S1A_IW_GRDH_1SDV_20170724T214346_20170724T214411_017619_01D7BE_DA1D.zip
S1A_IW_GRDH_1SDV_20170829T214348_20170829T214413_018144_01E7AE_B8CE.zip
S1A_IW_GRDH_1SDV_20171028T214255_20171028T214324_019019_02027F_A9F0.zip
S1A_IW_GRDH_1SDV_20170817T214347_20170817T214412_017969_01E264_4B99.zip
S1B_IW_GRDH_1SDV_20170811T214240_20170811T214308_006898_00C24E_B2AD.zip
S1A_IW_GRDH_1SDV_20170817T214253_20170817T214322_017969_01E264_30D8.zip
S1A_IW_GRDH_1SDV_20170817T214322_20170817T214347_017969_01E264_E56A.zip
S1A_IW_GRDH_1SDV_20171004T214255_20171004T214324_018669_01F7D5_F51A.zip
S1A_IW_GRDH_1SDV_20170822T215151_20170822T215216_018042_01E4A7_8E71.zip
S1B_IW_GRDH_1SDV_20170804T215040_20170804T215105_006796_00BF5A_107E.zip
S1B_IW_GRDH_1SDV_20170909T215013_20170909T215042_007321_00CE9F_4E20.zip
S1B_IW_GRDH_1SDV_20170804T215105_20170804T215131_006796_00BF5A_05A8.zip
S1A_IW_GRDH_1SDV_20170903T215126_20170903T215151_018217_01E9EE_8425.zip
S1A_IW_GRDH_1SDV_20170903T215057_20170903T215126_018217_01E9EE_DEBB.zip
S1A_IW_GRDH_1SDV_20170810T215150_20170810T215216_017867_01DF58_5144.zip
S1B_IW_GRDH_1SDV_20171108T215042_20171108T215107_008196_00E7C9_A8C6.zip
S1A_IW_GRDH_1SDV_20170810T215056_20170810T215125_017867_01DF58_2EDC.zip
S1B_IW_GRDH_1SDV_20171027T215043_20171027T215108_008021_00E2BF_9D8F.zip
S1B_IW_GRDH_1SDV_20170804T215011_20170804T215040_006796_00BF5A_D205.zip
S1B_IW_GRDH_1SDV_20171108T215013_20171108T215042_008196_00E7C9_48D6.zip
S1B_IW_GRDH_1SDV_20171027T215014_20171027T215043_008021_00E2BF_A9CA.zip
S1B_IW_GRDH_1SDV_20170816T215012_20170816T215041_006971_00C476_FA2C.zip
S1B_IW_GRDH_1SDV_20171108T215107_20171108T215133_008196_00E7C9_60B7.zip
S1B_IW_GRDH_1SDV_20171027T215108_20171027T215133_008021_00E2BF_46FE.zip
S1B_IW_GRDH_1SDV_20170816T215041_20170816T215106_006971_00C476_F284.zip
S1A_IW_GRDH_1SDH_20171023T091157_20171023T091226_018938_02000F_C7AD.zip
S1A_IW_GRDH_1SDV_20170729T215150_20170729T215215_017692_01DA02_0688.zip
S1A_IW_GRDH_1SDV_20170822T215126_20170822T215151_018042_01E4A7_D86A.zip
S1A_IW_GRDH_1SDV_20180206T215124_20180206T215149_020492_0230C6_9DB3.zip
S1A_IW_GRDH_1SDV_20170810T215125_20170810T215150_017867_01DF58_2669.zip
S1A_IW_GRDH_1SDV_20170822T215057_20170822T215126_018042_01E4A7_0F58.zip
S1B_IW_GRDH_1SDV_20170816T215106_20170816T215131_006971_00C476_A039.zip
S1B_IW_GRDH_1SDV_20170909T215042_20170909T215107_007321_00CE9F_D0F5.zip

At the contrary files well downloaded
S1A_IW_GRDH_1SDV_20180108T214347_20180108T214412_020069_022343_B906.zip
S1A_IW_GRDH_1SDV_20180201T214346_20180201T214411_020419_022E65_EC8E.zip
S1A_IW_GRDH_1SDV_20170910T214323_20170910T214348_018319_01ED1D_E048.zip
S1A_IW_GRDH_1SDV_20171203T214254_20171203T214323_019544_0212E3_C69F.zip
S1A_IW_GRDH_1SDV_20171215T214348_20171215T214413_019719_021857_D1B7.zip
S1A_IW_GRDH_1SDV_20180120T214321_20180120T214346_020244_0228D1_BCDC.zip
S1A_IW_GRDH_1SDV_20170922T214324_20170922T214349_018494_01F27C_3A45.zip
S1A_IW_GRDH_1SDV_20171227T214347_20171227T214412_019894_021DC4_94C7.zip
S1B_IW_GRDH_1SDV_20170904T214212_20170904T214241_007248_00CC74_FFFA.zip
S1A_IW_GRDH_1SDV_20171004T214349_20171004T214414_018669_01F7D5_2D41.zip
S1B_IW_GRDH_1SDV_20171221T214241_20171221T214309_008823_00FB62_4D29.zip
S1B_IW_GRDH_1SDV_20171010T214213_20171010T214242_007773_00DBA7_FBA3.zip
S1A_IW_GRDH_1SDV_20171203T214348_20171203T214413_019544_0212E3_6EE1.zip
S1B_IW_GRDH_1SDV_20171103T214213_20171103T214242_008123_00E5A6_23E9.zip
S1B_IW_GRDH_1SDV_20180114T214240_20180114T214308_009173_0106C1_7F29.zip
S1B_IW_GRDH_1SDV_20180126T214239_20180126T214308_009348_010C7A_74EA.zip
S1A_IW_GRDH_1SDV_20180201T214252_20180201T214321_020419_022E65_B79B.zip
S1A_IW_GRDH_1SDV_20170910T214254_20170910T214323_018319_01ED1D_B866.zip
S1B_IW_GRDH_1SDV_20180102T214240_20180102T214309_008998_01010F_3507.zip
S1B_IW_GRDH_1SDV_20180126T214210_20180126T214239_009348_010C7A_176D.zip
S1A_IW_GRDH_1SDV_20171215T214323_20171215T214348_019719_021857_B538.zip
S1A_IW_GRDH_1SDV_20180108T214322_20180108T214347_020069_022343_BC97.zip
S1A_IW_GRDH_1SDV_20180201T214321_20180201T214346_020419_022E65_720B.zip
S1A_IW_GRDH_1SDV_20180120T214252_20180120T214321_020244_0228D1_5778.zip
S1B_IW_GRDH_1SDV_20171115T214242_20171115T214310_008298_00EAE7_4584.zip
S1B_IW_GRDH_1SDV_20170904T214241_20170904T214309_007248_00CC74_E835.zip
S1B_IW_GRDH_1SDV_20171010T214242_20171010T214310_007773_00DBA7_CE61.zip
S1A_IW_GRDH_1SDV_20171227T214322_20171227T214347_019894_021DC4_C914.zip
S1A_IW_GRDH_1SDV_20171016T214255_20171016T214324_018844_01FD34_46C5.zip
S1A_IW_GRDH_1SDV_20170829T214254_20170829T214323_018144_01E7AE_CAF1.zip
S1B_IW_GRDH_1SDV_20180102T214211_20180102T214240_008998_01010F_98EC.zip
S1B_IW_GRDH_1SDV_20180114T214211_20180114T214240_009173_0106C1_DAE5.zip
S1A_IW_GRDH_1SDV_20170724T214321_20170724T214346_017619_01D7BE_8558.zip
S1B_IW_GRDH_1SDV_20170916T214242_20170916T214310_007423_00D19D_B083.zip
S1B_IW_GRDH_1SDV_20170916T214213_20170916T214242_007423_00D19D_947D.zip
S1B_IW_GRDH_1SDV_20171103T214242_20171103T214311_008123_00E5A6_231C.zip
S1B_IW_GRDH_1SDV_20171115T214213_20171115T214242_008298_00EAE7_14F0.zip
S1A_IW_GRDH_1SDV_20170922T214255_20170922T214324_018494_01F27C_FE37.zip
S1A_IW_GRDH_1SDV_20171215T214254_20171215T214323_019719_021857_045C.zip
S1A_IW_GRDH_1SDV_20180120T214346_20180120T214411_020244_0228D1_EA2E.zip
S1A_IW_GRDH_1SDV_20171121T214255_20171121T214324_019369_020D6C_055A.zip
S1A_IW_GRDH_1SDV_20171203T214323_20171203T214348_019544_0212E3_CBBC.zip
S1B_IW_GRDH_1SDV_20171221T214212_20171221T214241_008823_00FB62_4A82.zip
S1A_IW_GRDH_1SDV_20180108T214253_20180108T214322_020069_022343_4EB5.zip
S1A_IW_GRDH_1SDV_20171227T214253_20171227T214322_019894_021DC4_998F.zip
S1B_IW_GRDH_1SDV_20171209T214212_20171209T214241_008648_00F5D1_0893.zip
S1B_IW_GRDH_1SDV_20171209T214241_20171209T214310_008648_00F5D1_0132.zip
S1A_IW_GRDH_1SDV_20170922T214349_20170922T214414_018494_01F27C_899C.zip
S1A_IW_GRDH_1SDV_20171121T214349_20171121T214414_019369_020D6C_B2D9.zip
S1A_IW_GRDH_1SDV_20171016T214324_20171016T214349_018844_01FD34_97C1.zip
S1A_IW_GRDH_1SDV_20171121T214324_20171121T214349_019369_020D6C_5D62.zip
S1A_IW_GRDH_1SDV_20171016T214349_20171016T214414_018844_01FD34_E101.zip
S1B_IW_GRDH_1SDV_20170928T214213_20170928T214242_007598_00D6A3_EF3C.zip
S1B_IW_GRDH_1SDV_20170928T214242_20170928T214310_007598_00D6A3_32BF.zip
S1B_IW_GRDH_1SDV_20171127T214213_20171127T214242_008473_00F044_4E1B.zip
S1B_IW_GRDH_1SDV_20171127T214242_20171127T214310_008473_00F044_2E53.zip
S1A_IW_GRDH_1SDV_20171102T215059_20171102T215128_019092_0204C2_0611.zip
S1B_IW_GRDH_1SDV_20180131T215040_20180131T215105_009421_010EE9_770D.zip
S1A_IW_GRDH_1SDV_20171208T215151_20171208T215217_019617_021535_0FDE.zip
S1B_IW_GRDH_1SDV_20170921T215013_20170921T215042_007496_00D3BE_CEA6.zip
S1B_IW_GRDH_1SDV_20180107T215041_20180107T215106_009071_010379_DF62.zip
S1B_IW_GRDH_1SDV_20171202T215107_20171202T215133_008546_00F29F_8589.zip
S1A_IW_GRDH_1SDV_20171102T215128_20171102T215153_019092_0204C2_63A9.zip
S1A_IW_GRDH_1SDV_20171021T215153_20171021T215218_018917_01FF74_4E44.zip
S1A_IW_GRDH_1SDH_20171104T091226_20171104T091254_019113_020564_3FD7.zip
S1A_IW_GRDH_1SDV_20170927T215152_20170927T215218_018567_01F4BD_2159.zip
S1B_IW_GRDH_1SDV_20171226T215106_20171226T215132_008896_00FDC6_851A.zip
S1A_IW_GRDH_1SDV_20180125T215056_20180125T215125_020317_022B30_B31E.zip
S1A_IW_GRDH_1SDH_20171104T091157_20171104T091226_019113_020564_1559.zip
S1A_IW_GRDH_1SDV_20171114T215058_20171114T215127_019267_020A38_9E74.zip
S1A_IW_GRDH_1SDV_20170915T215127_20170915T215152_018392_01EF62_520A.zip
S1A_IW_GRDH_1SDV_20171208T215057_20171208T215126_019617_021535_34E7.zip
S1B_IW_GRDH_1SDV_20171003T215014_20171003T215043_007671_00D8C2_152B.zip
S1A_IW_GRDH_1SDH_20180103T091155_20180103T091224_019988_0220C0_F543.zip
S1A_IW_GRDH_1SDH_20171128T091156_20171128T091225_019463_021062_C4FC.zip
S1A_IW_GRDH_1SDV_20171220T215057_20171220T215126_019792_021AA8_8666.zip
S1A_IW_GRDH_1SDV_20171114T215152_20171114T215218_019267_020A38_2704.zip
S1B_IW_GRDH_1SDV_20171214T215013_20171214T215042_008721_00F82C_81A4.zip
S1A_IW_GRDH_1SDV_20171126T215152_20171126T215217_019442_020FC2_BFED.zip
S1A_IW_GRDH_1SDV_20171009T215058_20171009T215127_018742_01FA0D_3F88.zip
S1B_IW_GRDH_1SDV_20171003T215043_20171003T215108_007671_00D8C2_A0D4.zip
S1A_IW_GRDH_1SDV_20171126T215058_20171126T215127_019442_020FC2_322E.zip
S1A_IW_GRDH_1SDV_20170903T215151_20170903T215217_018217_01E9EE_EF29.zip
S1A_IW_GRDH_1SDV_20171126T215127_20171126T215152_019442_020FC2_1A9F.zip
S1B_IW_GRDH_1SDV_20171120T215042_20171120T215107_008371_00ED21_2B4A.zip
S1A_IW_GRDH_1SDV_20171021T215059_20171021T215128_018917_01FF74_C7BF.zip
S1A_IW_GRDH_1SDV_20171114T215127_20171114T215152_019267_020A38_8EA3.zip
S1A_IW_GRDH_1SDH_20180103T091224_20180103T091252_019988_0220C0_129A.zip
S1B_IW_GRDH_1SDV_20170921T215107_20170921T215133_007496_00D3BE_C4E9.zip
S1A_IW_GRDH_1SDV_20171009T215152_20171009T215218_018742_01FA0D_2455.zip
S1B_IW_GRDH_1SDV_20180107T215106_20180107T215131_009071_010379_9B07.zip
S1B_IW_GRDH_1SDV_20180119T215040_20180119T215105_009246_01092B_CF04.zip
S1B_IW_GRDH_1SDV_20171120T215013_20171120T215042_008371_00ED21_F9ED.zip
S1A_IW_GRDH_1SDV_20170915T215152_20170915T215217_018392_01EF62_1A7A.zip
S1A_IW_GRDH_1SDV_20170927T215127_20170927T215152_018567_01F4BD_0444.zip
S1B_IW_GRDH_1SDV_20171202T215042_20171202T215107_008546_00F29F_C125.zip
S1B_IW_GRDH_1SDV_20171202T215013_20171202T215042_008546_00F29F_150B.zip
S1A_IW_GRDH_1SDV_20171220T215126_20171220T215151_019792_021AA8_DC55.zip
S1A_IW_GRDH_1SDH_20180115T091154_20180115T091223_020163_02264B_D99B.zip
S1A_IW_GRDH_1SDH_20180127T091154_20180127T091223_020338_022BD6_A02C.zip
S1A_IW_GRDH_1SDV_20171102T215153_20171102T215218_019092_0204C2_7A33.zip
S1B_IW_GRDH_1SDV_20170909T215107_20170909T215132_007321_00CE9F_B8B9.zip
S1A_IW_GRDH_1SDV_20180101T215150_20180101T215216_019967_02201B_3497.zip
S1B_IW_GRDH_1SDV_20171015T215043_20171015T215108_007846_00DDAE_3945.zip
S1B_IW_GRDH_1SDV_20180131T215105_20180131T215130_009421_010EE9_203D.zip
S1A_IW_GRDH_1SDV_20180113T215056_20180113T215125_020142_0225A4_7611.zip
S1B_IW_GRDH_1SDV_20180131T215011_20180131T215040_009421_010EE9_F345.zip
S1A_IW_GRDH_1SDV_20180101T215056_20180101T215125_019967_02201B_2307.zip
S1B_IW_GRDH_1SDV_20180119T215105_20180119T215131_009246_01092B_253B.zip
S1B_IW_GRDH_1SDV_20171226T215041_20171226T215106_008896_00FDC6_EB33.zip
S1B_IW_GRDH_1SDV_20170921T215042_20170921T215107_007496_00D3BE_5FC9.zip
S1B_IW_GRDH_1SDV_20171015T215108_20171015T215133_007846_00DDAE_C338.zip
S1A_IW_GRDH_1SDV_20170729T215056_20170729T215125_017692_01DA02_94C9.zip
S1A_IW_GRDH_1SDV_20171208T215126_20171208T215151_019617_021535_491B.zip
S1A_IW_GRDH_1SDV_20170729T215125_20170729T215150_017692_01DA02_286C.zip
S1B_IW_GRDH_1SDV_20171003T215108_20171003T215133_007671_00D8C2_5B55.zip
S1A_IW_GRDH_1SDV_20180125T215125_20180125T215150_020317_022B30_D4FF.zip
S1B_IW_GRDH_1SDV_20171120T215107_20171120T215133_008371_00ED21_F73E.zip
S1B_IW_GRDH_1SDV_20171015T215014_20171015T215043_007846_00DDAE_AD40.zip
S1B_IW_GRDH_1SDV_20180119T215011_20180119T215040_009246_01092B_BCCC.zip
S1A_IW_GRDH_1SDV_20180113T215150_20180113T215216_020142_0225A4_3499.zip
S1A_IW_GRDH_1SDV_20170915T215058_20170915T215127_018392_01EF62_D7B9.zip
S1A_IW_GRDH_1SDV_20171009T215127_20171009T215152_018742_01FA0D_E60E.zip
S1B_IW_GRDH_1SDV_20171226T215012_20171226T215041_008896_00FDC6_4CDC.zip
S1A_IW_GRDH_1SDV_20180113T215125_20180113T215150_020142_0225A4_99A9.zip
S1A_IW_GRDH_1SDV_20171220T215151_20171220T215216_019792_021AA8_37D3.zip
S1B_IW_GRDH_1SDV_20171214T215107_20171214T215132_008721_00F82C_1B64.zip
S1A_IW_GRDH_1SDV_20170927T215058_20170927T215127_018567_01F4BD_076C.zip
S1B_IW_GRDH_1SDV_20180107T215012_20180107T215041_009071_010379_485B.zip
S1A_IW_GRDH_1SDH_20180115T091223_20180115T091252_020163_02264B_E8A9.zip
S1A_IW_GRDH_1SDH_20180127T091223_20180127T091251_020338_022BD6_1352.zip
S1A_IW_GRDH_1SDV_20180101T215125_20180101T215150_019967_02201B_CFB3.zip
S1A_IW_GRDH_1SDH_20171023T091226_20171023T091254_018938_02000F_9EB1.zip
S1A_IW_GRDH_1SDH_20171128T091225_20171128T091254_019463_021062_178E.zip
S1A_IW_GRDH_1SDV_20180125T215150_20180125T215215_020317_022B30_5C9E.zip
S1A_IW_GRDH_1SDV_20171021T215128_20171021T215153_018917_01FF74_5BF6.zip
S1B_IW_GRDH_1SDV_20171214T215042_20171214T215107_008721_00F82C_E2EA.zip

Sentinel_Sensor = 'S1'
Product_Type = 'GRD' 
Sensor_Mode = 'IW' 
Polarisation = 'VV VH'
Relative_Orbit_To_Process 120 and 47
Start_Date = '2016-11-01'
End_Date = '2018-02-10'

**Comment by olivierhagolle** [comment]
Hi Cedric, I have made some updates, which worked on Sentinel2. I did not test for Sentinel1.
The PEPS team is preparing a new tool that will be faster and more easily maintained than mine.
It should be ready in a few weeks.
Best regards,
Olivier
