### ISSUE TITLE
prod' referenced before assignment

### ISSUE THREAD

**Issue by mzjan** [olivierhagolle/peps_download#16]
In function parse_catalog, when len(data["features"]) == 0 loop is not starting, prod is not assign so it can't be returned. This should be fixed. 

https://github.com/olivierhagolle/peps_download/blob/65d14034753ca1de9965d39df1f8d16ad31fdcb0/peps_download.py#L80

**Comment by olivierhagolle** [comment]
Done, thanks !
Olivier
