### ISSUE TITLE
Products on tape don't download

### ISSUE THREAD

**Issue by maximlamare** [olivierhagolle/peps_download#17]
When downloading Sentinel 3 scenes, all the files are downloaded. However, the products that are on tape are skipped and the resulting zip file are 0 bytes. The products on disk are retrieved correctly.
No error messages to signal.

**Comment by olivierhagolle** [comment]
Bonjour Maxime
peps-download is innocent, peps is guilty
https://peps-mission.cnes.fr/fr/peps-info-telechargement-de-produits-sur-bande-impossible

They say you can send a list of the products you need, and they will put them on disk manually.
Please contact them with mailto:exppeps@cnes.fr
Olivier
