### ISSUE TITLE
Script exits when products are still in "staging" status

### ISSUE THREAD

**Issue by raffaelegaetano** [olivierhagolle/peps_download#18]
All in the title. 
If I got it well, at the end of the script, code only checks for product still in "tape" status to decide whether restart or exit. My simple workaround, which seems to work properly, in the attached file (diff sybtax).
[staging.txt](https://github.com/olivierhagolle/peps_download/files/2378965/staging.txt)

**Comment by olivierhagolle** [comment]
Thanks Raffaele 
Yes of course !
Olivier

**Comment by olivierhagolle** [comment]
I had done it too, but not committed nor pushed. I just did it, thanks for pushing me !
Olivier

**Comment by Tossawon** [comment]
Dear all, 
    I am suffering this issue as the mention above. All "disk " can be downloaded but "tape" and "stage" cannot be downloaded. Do you have any solutions to solve this ? If its possible, could you sent me an email the "peps_download.py" which is solved.

Thank you.

tossawon120@gmail.com

**Comment by olivierhagolle** [comment]
Hi, 
I tested it over a case this morning, and the script works and the products on tape are staged then put on disk and downloaded. Maybe when you did the test was there a failure or maintenance of the PEPS robot system which downloads the products from tapes.

However, I noticed, in my example, that one product which should have been staged, stayed on tape. For this one, I had to start again the same command. I do not know why it was not staged in the first place...

Please try again and  tell me
Best regards,
Olivier
