### ISSUE TITLE
Error downloading test files

### ISSUE THREAD

**Issue by NicWayand** [olivierhagolle/peps_download#2]
Hello, I am trying to download sentinel-2 data. I got a PEPS password which works on the PEPS website. But I get the below error trying one of the suggested download calls. Any suggestions (or other alternative methods for bulk sentinel-2 data) are appreciated. 

```
 python ./peps_download.py -c S2 --lon 1 --lat 43.5 -a peps.txt -d 2015-11-01 -f 2015-12-01
curl -k -o search.json https://peps.cnes.fr/resto/api/collections/S2/search.json?lat=43.500000\&lon=1.000000\&startDate=2015-11-01\&completionDate=2015-12-01\&maxRecords=500
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 50304    0 50304    0     0  38479      0 --:--:--  0:00:01 --:--:-- 38517
S2A_OPER_PRD_MSIL1C_PDMC_20151202T224525_R008_V20151130T105641_20151130T105641 2015-11-30T10:56:41Z
S2A_OPER_PRD_MSIL1C_PDMC_20160309T091505_R051_V20151113T105818_20151113T105818 2015-11-13T10:58:18Z
S2A_OPER_PRD_MSIL1C_PDMC_20160715T112823_R051_V20151113T105818_20151113T105818 2015-11-13T10:58:18Z
./tmp.tmp
curl -o ./tmp.tmp -k -u EMAIL:PASSWORD https://peps.cnes.fr/resto/collections/S2/65001467-4472-5d22-b552-5d611ddd0346/download/?issuerId=peps
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    44  100    44    0     0     54      0 --:--:-- --:--:-- --:--:--    54
Result is a text file
{u'ErrorCode': 404, u'ErrorMessage': u'Not Found'}

```

**Comment by olivierhagolle** [comment]
Hi,
sorry for being quite long to answer, I am lacking time these days. Usually, I get this message when the authentication file is wrong. The command line works for me.

Could you please check the curl command line works for you (probably it doesn't), check your email and password, and modify the peps.txt file accordingly ?

Best regards,
Olivier

**Comment by NicWayand** [comment]
Sorry what curl command are you referring to?

I checked my email and password in the file, and it matches what allows me to log into https://peps.cnes.fr/rocket/#/signin. 

So I am stumped what to try next?

**Comment by NicWayand** [comment]
I created a new username/password and that did the trick! Not sure why my old one didn't work, but its working downloading now. Thanks!
