### ISSUE TITLE
Problem with searching data

### ISSUE THREAD

**Issue by mzjan** [olivierhagolle/peps_download#21]
I suppose that resto service for searching data in peps repo has changed. I can't get any data with use of peps_download. I  tried to get the search service directly as bellow:

https://peps.cnes.fr/resto/api/collections/S2ST/search.json?box=14.0,49.0,24.0,55.0\&startDate=2018-05-01\&completionDate=2018-06-01\&maxRecords=5000

And I'm getting error:
{"ErrorMessage":"Value for \"box\" must follow the pattern ^[0-9\\.\\,\\-]*$","ErrorCode":400}

Have you any documentation of peps API? Or can you confirm that something was changed, and what?

**Comment by olivierhagolle** [comment]
Hi, 

the request below, pasted to the browser, seems to work:
https://peps.cnes.fr/resto/api/collections/S2ST/search.json?box=14.0,49.0,24.0,55.0&startDate=2018-05-01&completionDate=2018-06-01&maxRecords=5000

So it seems a matter of protecting special characters before sending request to Curl.
Could you please provide the command line used for peps_download ?
Are you working  under Linux or Windows ?

Olivier

**Comment by mzjan** [comment]
Hi,

thanks for quick reply. You have right, the problem was with escaping special character (that's weird because I use debian, and I haven't had any problem with this code before,). I had old version of your lib, after upgrading this error doesn't occur. 

Janek
