### ISSUE TITLE
problem with parsing data to download

### ISSUE THREAD

**Issue by mzjan** [olivierhagolle/peps_download#22]
I download new version of this project. After setting my user name and password in peps.txt. I did example:

`python ./peps_download.py -c S2ST -l 'Toulouse' -a peps.txt -d 2017-01-01 -f 2017-02-0`

as response to console I recived:

`curl -k -o search.json https://peps.cnes.fr/resto/api/collections/S2ST/search.json?q=Toulouse\&startDate=2017-01-01\&completionDate=2017-02-01\&maxRecords=500
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 16671    0 16671    0     0  25079      0 --:--:-- --:--:-- --:--:-- 25069
(u'S2A_MSIL1C_20170126T105321_N0204_R051_T31TCJ_20170126T105612', u'unknown')
(u'S2A_MSIL1C_20170116T105401_N0204_R051_T31TCJ_20170116T105355', u'unknown')
##########################
2  products to download
##########################
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 16671    0 16671    0     0  27746      0 --:--:-- --:--:-- --:--:-- 27785
(u'S2A_MSIL1C_20170126T105321_N0204_R051_T31TCJ_20170126T105612', u'unknown')
(u'S2A_MSIL1C_20170116T105401_N0204_R051_T31TCJ_20170116T105355', u'unknown')`

Nothing was download. I look into a code and I found that there is a problem in parse_catalog function.  In line 63
`print(prod, data["features"][i]["properties"]["storage"]["mode"])`
data["features"][i]["properties"]["storage"]["mode"] # this is unknown
Some error occurs but is handled by simple pass in line 96

**Comment by olivierhagolle** [comment]
This is another issue, not on peps_download, but on PEPS itself : the "unknown" status should not exist.
I have been told it will be solved next week. For questions related to PEPS, please ask peps support:
exppeps@cnes.fr

Best regards,
Olivier

**Comment by mzjan** [comment]
Yes, I just found in json "storage":{"mode":"unknown"}}}

Thank you for support. Regards
Janek

**Comment by olivierhagolle** [comment]
Hi, Mzjan, 
just to let you know that the issue with "unknow" status on peps was solved on peps.
Best regards,
Olivier
