### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 'search.json'

### ISSUE THREAD

**Issue by kylefelipe** [olivierhagolle/peps_download#23]
Hi!
Im from Brazil.

Using the following line: 
`$ python peps_download.py -c S2ST -a peps.txt -t 23kks -d 2018-01-01 -f 2018-12-27 -w /home/x12239181/Documentos/sentinel/teste_python/`
I got this:
`curl -k -o search.json https://peps.cnes.fr/resto/api/collections/S2ST/search.json?tileid=23kks\&startDate=2018-01-01\&completionDate=2018-12-27\&maxRecords=500
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:02:10 --:--:--     0curl: (7) Failed to connect to peps.cnes.fr port 443: Tempo esgotado para conexão
Traceback (most recent call last):
  File "peps_download.py", line 276, in <module>
    prod, download_dict, storage_dict, size_dict = parse_catalog(options.search_json_file)
  File "peps_download.py", line 47, in parse_catalog
    with open(search_json_file) as data_file:
**IOError: [Errno 2] No such file or directory: 'search.json'**`

My S.O.: Debian 9
Python: 2.7.15

**Comment by olivierhagolle** [comment]
Hi
the issue is here "Failed to connect to peps.cnes.fr port 443" does your internet provider allow this connection ? Do you need to go through a proxy ?

In my case, it works, except that the tile number must be in caps letters : 23KKS.
Olivier

**Comment by heigre** [comment]
Hi!

I'm getting the same error when trying the example commands, e.g.:
python ./peps_download.py -l 'Toulouse' -a peps.txt -d 2016-12-06 -f 2017-02-01 -c S2ST

Nothing blocking on port 443.

OS: Ubuntu 18.04 LTS 
Python: 2.7.15+

Mats

**Comment by olivierhagolle** [comment]
Hi Mats,
I just tried this command line and it worked. Maybe the network, or PEPS, were offline for a moment ? Could you please retry ?
Olivier

```
hagolleo@s2calc:~/PROG/S2/peps_download$ python ./peps_download.py -l 'Toulouse' -a hagolle.txt -d 2016-12-06 -f 2017-02-01 -c S2ST
curl -k -o search.json https://peps.cnes.fr/resto/api/collections/S2ST/search.json?q=Toulouse\&startDate=2016-12-06\&completionDate=2017-02-01\&maxRecords=500
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 39139    0 39139    0     0   103k      0 --:--:-- --:--:-- --:--:--  103k
(u'S2A_MSIL1C_20161207T105432_N0204_R051_T31TCJ_20161207T105428', u'disk')
(u'S2A_MSIL1C_20161227T105442_N0204_R051_T31TCJ_20161227T105527', u'disk')
(u'S2A_MSIL1C_20170116T105401_N0204_R051_T31TCJ_20170116T105355', u'disk')
(u'S2A_MSIL1C_20161217T105442_N0204_R051_T31TCJ_20161217T105440', u'disk')
(u'S2A_MSIL1C_20170126T105321_N0204_R051_T31TCJ_20170126T105612', u'disk')
##########################
5  products to download
##########################
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 39138    0 39138    0     0   103k      0 --:--:-- --:--:-- --:--:--  103k
(u'S2A_MSIL1C_20161207T105432_N0204_R051_T31TCJ_20161207T105428', u'disk')
(u'S2A_MSIL1C_20161227T105442_N0204_R051_T31TCJ_20161227T105527', u'disk')
(u'S2A_MSIL1C_20170116T105401_N0204_R051_T31TCJ_20170116T105355', u'disk')
(u'S2A_MSIL1C_20161217T105442_N0204_R051_T31TCJ_20161217T105440', u'disk')
(u'S2A_MSIL1C_20170126T105321_N0204_R051_T31TCJ_20170126T105612', u'disk')

Download of product : S2A_MSIL1C_20161207T105432_N0204_R051_T31TCJ_20161207T105428
curl -o ./tmp_1571244647.72.tmp -k -u "myself:secret" https://peps.cnes.fr/resto/collections/S2ST/59ed2705-2e18-5284-973c-03f913b1a00a/down
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  749M  100  749M    0     0  59.9M      0  0:00:12  0:00:12 --:--:-- 85.1M
(785893279, 785893279)
product saved as : ./S2A_MSIL1C_20161207T105432_N0204_R051_T31TCJ_20161207T105428.zip
...
```

**Comment by heigre** [comment]
Thanks for the über-fast reply Oliver!
It seems to be working now, thank you! 
Mats

**Comment by olivierhagolle** [comment]
Great Thanks
