### ISSUE TITLE
Sentinel 1 A or B

### ISSUE THREAD

**Issue by dsanchezalamolwd** [olivierhagolle/peps_download#25]
Hi, how can I download only from sentinel 1 A or B data? In the script I just can download S1 Data.
Sorry for my english and thanks.

**Comment by olivierhagolle** [comment]
Hi,
I just added this feature, using --sat option
Example:
python peps_download.py --lon 1 --lat 44 -a peps.txt -d 2019-01-01 -f 2019-02-01 --sat S1B  -c S1 

Enjoy ;)
Olivier

**Comment by dsanchezalamolwd** [comment]
Thanks for the code, you are really helpfull!
