### ISSUE TITLE
Trouble with S2ST mode

### ISSUE THREAD

**Issue by bergsmaE** [olivierhagolle/peps_download#34]
In case I use S2ST mode the search breaks:

**syntax:**
python peps_download.py -c S2ST -l 'Toulouse' -a peps.txt -d 2017-01-01 -f 2017-02-01

**return:**
'startDate' is not recognized as an internal or external command,
operable program or batch file.
'completionDate' is not recognized as an internal or external command,
operable program or batch file.
'maxRecords' is not recognized as an internal or external command,
operable program or batch file.

The code finds just the disk-available data and discards the imposed date-limits

In case of a tile number, it gets worse:
**syntax:**
python peps_download.py -c S2ST -t 31TCJ -a peps.txt -d 2017-01-01 -f 2017-02-01

**return:**
'startDate' is not recognized as an internal or external command,
operable program or batch file.
'completionDate' is not recognized as an internal or external command,
operable program or batch file.
'maxRecords' is not recognized as an internal or external command,
operable program or batch file.
Value for "tileid" must follow the pattern ^[0-6][0-9][A-Za-z]([A-Za-z]){0,2}%?$

What I can think of, either the parser is not working properly or the curl link rules to the database have changed.
Any suggestions?

**Comment by bergsmaE** [comment]
This issue is not relevant anymore, it was related to my local python settings.

**Comment by olivierhagolle** [comment]
I like that, Issues that get solved without interventions from us. But maybe could you detail a little more how you solved it, in case it happens to someone else.
Thanks
Olivier

**Comment by bergsmaE** [comment]
Hi Olivier, sure but I am not very proud of it: I have created a clean new python 2.7.17 environment and that solved it for me. I did not further investigate.
