### ISSUE TITLE
peps - limited data download

### ISSUE THREAD

**Issue by edubeiral** [olivierhagolle/peps_download#35]
Hello everyone,
I'm using the peps tool to download Sentinel 2 data from 2016 to 2020 from a specific area. But I'm having the trouble that the tool downloads only 500 files, and if I try to download them again, the terminal show me the message that the 500 files are already on the folder, and doesn't download the other days that I need. Those 500 files are from 2020 to November 2019. Again, I need until 2016.

Is it a limit of the tool that can only download 500 files?

If anybody can help me, I'd be kindly grateful...Thanks for the help!!!

That's the my input line to download the files:
`python ./peps_download.py -c S2ST --lonmin -41.1 --lonmax -38.5 --latmin -22.1 --latmax -17.5 -a peps.txt -d 2016-01-01 -f 2020-01-01`

**Comment by bergsmaE** [comment]
This depends on the search-string:

search_catalog = 'curl -k -o %s https://peps.cnes.fr/resto/api/collections/%s/search.json?%s\&startDate=%s\&completionDate=%s\&maxRecords=500' % ( options.search_json_file, options.collection, query_geom, start_date, end_date)

In this string you will find: &maxRecords=500

You can change this in your file or make an input option; might perhaps  be nice to do the latter.

Have a great weekend,


Erwin


On 24 Jan 2020, at 17:37, edubeiral <notifications@github.com<mailto:notifications@github.com>> wrote:

Hello everyone,
I'm using the peps tool to download Sentinel 2 data from 2016 to 2020 from a specific area. But I'm having the trouble that the tool downloads only 500 files, and if I try to download them again, the terminal show me the message that the 500 hundred files are already on the folder, and doesn't download the other days that I need.
Is it a limit of the tool that can only download 500 files?
If anybody can help me, I'd be kindly grateful...Thanks for the help!!!
That's the my input line to download the files:
python ./peps_download.py -c S2ST --lonmin -41.1 --lonmax -38.5 --latmin -22.1 --latmax -17.5 -a peps.txt -d 2016-01-01 -f 2019-12-01

**Comment by edubeiral** [comment]
Thanks for the help Mr. Erwin.

I tried changing the "&maxRecords=500" values on the  _peps_download.py_ file to 5000, but it didn't work. 

So, if you don't mind, how could I make this input option? As you mentioned, would be probably better trying this option

Once again, thank you!

**Comment by olivierhagolle** [comment]
Hi, there is indeed a limitation in the number of products you may retrieve in one command from PEPS. The origin is not peps_download.py, but PEPS itself. I can only recommend to either reduce the surface or the time duration in your query. 

Olivier

**Comment by edubeiral** [comment]
Ok Mr. Olivier, thank you, I'm doing that. 

Another thing that I would like to ask - which I searched here https://github.com/olivierhagolle/peps_download/blob/master/peps_download.py - but didn't understood well, is the reason why this message appear to me in peps, and why does it happens: 

`# remaining products are on tape, lets's wait 1 minute before trying again`

**Comment by olivierhagolle** [comment]
Hi, it is explained in the first lines of the readme file ;)
Olivier
