### ISSUE TITLE
Add tile ID to readme

### ISSUE THREAD

**Issue by schckngs** [olivierhagolle/peps_download#41]
Hi, this is a small request to add an example with the tile ID option to the Readme?

I had initially defined the tileid '-t' parameter wrong and retrieved the error:
`Value for "tileid" must follow the pattern ^[0-6][0-9][A-Za-z]([A-Za-z]){0,2}%?$`

It is working fine now that I am using it properly but might be helpful for new users to have it obvious in the examples.

Thanks so much for sharing this! I am using python 3 and it's working great, really speeding up S2 downloads. Cheers.

**Comment by sac3g15** [comment]
Are you using windows? I am currently trying to run the code on there and have opened a python 3.8 command line window. Then navigated to the peps folder and tried to run the following:

python3 peps_download.py -c S2ST --lonmin -87.81 --lat 17.40 -a peps.txt -d 2018-12-01 -f 2019-01-01 -t 16QDE -p S2MSI1C

it is saying invalid syntax though.. any thoughts on why ?

**Comment by olivierhagolle** [comment]
Hi, the same command works for me on Python 3.6 (I have not installed 3.8 yet)
Olivier

[hagolle@visu06 peps_download]$ python3 peps_download.py -c S2ST --lonmin -87.81 --lat 17.40 -a peps.txt -d 2018-12-01 -f 2019-01-01 -t 16QDE -p S2MSI1C
curl -k -o search.json https://peps.cnes.fr/resto/api/collections/S2ST/search.json?tileid=16QDE\&startDate=2018-12-01\&completionDate=2019-01-01\&maxRecords=500\&productType=S2MSI1C\&sensorMode=
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 69466    0 69466    0     0   150k      0 --:--:-- --:--:-- --:--:--  151k
S2B_MSIL1C_20181231T162659_N0207_R040_T16QDE_20181231T194948 disk
S2B_MSIL1C_20181228T161659_N0207_R140_T16QDE_20181228T194416 disk
S2A_MSIL1C_20181226T162701_N0207_R040_T16QDE_20181226T182057 disk
S2A_MSIL1C_20181223T161701_N0207_R140_T16QDE_20181223T193348 tape
S2B_MSIL1C_20181218T161659_N0207_R140_T16QDE_20181218T194450 tape
S2A_MSIL1C_20181216T162701_N0207_R040_T16QDE_20181216T182239 disk
S2A_MSIL1C_20181213T161651_N0207_R140_T16QDE_20181213T193323 tape
S2B_MSIL1C_20181211T162649_N0207_R040_T16QDE_20181211T194314 disk
S2B_MSIL1C_20181208T161639_N0207_R140_T16QDE_20181208T194450 tape
S2A_MSIL1C_20181206T162641_N0207_R040_T16QDE_20181206T182302 disk
S2A_MSIL1C_20181203T161631_N0207_R140_T16QDE_20181203T194507 disk
S2B_MSIL1C_20181201T162629_N0207_R040_T16QDE_20181201T194958 disk

**Comment by olivierhagolle** [comment]
@schckngs

Good suggestion, I am updating the readme

**Comment by sac3g15** [comment]
Thanks for the fast reply, 

![image](https://user-images.githubusercontent.com/61827916/98844813-c5cf3800-2444-11eb-8465-6cdd86acb315.png)

In the python command prompt and anaconda prompt, both run with no error but I get no diagnostics or results...

**Comment by olivierhagolle** [comment]
Difficult for me to help, it might be related to some windows issues, but I know nothing of windows, and peps_download is only tested on linux. Maybe you'll find some help here or around you ?

**Comment by sac3g15** [comment]
Alright, no problem! Appreciate the help and the code - super helpful
