### ISSUE TITLE
Value for "lat" must be numeric

### ISSUE THREAD

**Issue by Sananvalinta** [olivierhagolle/peps_download#45]
Hello,
I try to run the example code: python ./peps_download.py -c S2 --lon 1 --lat 43.5 -a peps.txt -d 2015-11-01 -f 2015-12-01 -o 51
but get this error: Value for "lat" must be numeric
does anyone have an idea what might be wrong?
Best

**Comment by olivierhagolle** [comment]
Hi,
I just tested it with python 2.7 and 3.7,, and I don't have this issue (see below). If you manage to solve it, you will need to replace -c S2 by -c S2ST, as all the S2 products are now on single tile products. I'll make a change to the documentation.
Best regards
Olivier
'``
python ./peps_download.py -c S2ST --lon 1 --lat 43.5 -a peps.txt -d 2015-11-01 -f 2015-12-01 -o 51
**** products before '2016-12-05' are stored in non-tiled products collection
**** please use option -c S2
curl -k -o search.json https://peps.cnes.fr/resto/api/collections/S2ST/search.json?lat=43.500000\&lon=1.000000\&startDate=2015-11-01\&completionDate=2015-12-01\&maxRecords=500
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8675    0  8675    0     0  22298      0 --:--:-- --:--:-- --:--:-- 22416
S2A_MSIL1C_20151113T105302_N0204_R051_T31TCJ_20151113T105818 tape

Stage tape product: S2A_MSIL1C_20151113T105302_N0204_R051_T31TCJ_20151113T105818
##########################
1  products to download
##########################
```

**Comment by Sananvalinta** [comment]
Hell and thank you for the fast answer,
I still have the problem (I run it with python 2.7.15 and 3.8.2) you think it can be a problem that I try to run it on Windows?
Best,

**Comment by olivierhagolle** [comment]
It might be, but I work on Linux, and did not test-it there.
Could it be also a question of language ? For instance in France, we use "," instead of "." as decimal separator.
On windows, there is the mobaxterm solution, that runs linux terminals under windows and it can also install curl.

**Comment by olivierhagolle** [comment]
Could you please show the https request it has written on your terminal ?

**Comment by Sananvalinta** [comment]
I get the same error without decimal separator:

(py27) C:\Users\jhammar\Anaconda3\envs\py27>python ./peps_download.py -c S2ST --lon 1 --lat 43 -a peps.txt -d 2015-11-01 -f 2015-12-01 -o 51
**** products before '2016-12-05' are stored in non-tiled products collection
**** please use option -c S2
curl -k -o search.json https://peps.cnes.fr/resto/api/collections/S2ST/search.json?lat=43.000000\&lon=1.000000\&startDate=2015-11-01\&completionDate=2015-12-01\&maxRecords=500
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    68  100    68    0     0    147      0 --:--:-- --:--:-- --:--:--   146
'lon' is not recognized as an internal or external command,
operable program or batch file.
'startDate' is not recognized as an internal or external command,
operable program or batch file.
'completionDate' is not recognized as an internal or external command,
operable program or batch file.
'maxRecords' is not recognized as an internal or external command,
operable program or batch file.
Value for "lat" must be numeric

**Comment by olivierhagolle** [comment]
OK, thanks. I guess it is a matter of protection of special characters in the strings on windows. Maybe the "=" or "?"sign. I think someone had proposed a solution for that in one of my tools. I will look for that tomorrow.
Olivier

**Comment by bergsmaE** [comment]
Yes i wanted to write the same;
@olivierhagolle  no need to change, it is already in the code.

I don’t think it is a language problem, in the end it is python. So more a system problem. I see you’re on windows, did you add “--windows”, that might help ;-) because your curl commend thinks you are in linux.

For your info; (it is “\\&” for linux and “^&” for windows)

Cheers,


Erwin

**Comment by Sananvalinta** [comment]
Hello,
it seem to work with the --windows 
Thanks a lot :)
