### ISSUE TITLE
dates not working as expected

### ISSUE THREAD

**Issue by negroscuro** [olivierhagolle/peps_download#5]
Asking from 10th january to 10th january:

python peps_download.py -c S2 -a /home/atos/cron/peps.txt -w /home/atos/cron/downloads -d 2016-01-10 -f 2016-01-10 --latmin=48.6197 --lonmin=13.9898 --latmax=50.3805 --lonmax=17.6958

This request show no results

Now asking from 11th january to 11th january:
python peps_download.py -c S2 -a /home/atos/cron/peps.txt -w /home/atos/cron/downloads -d 2016-01-11 -f 2016-01-11 --latmin=48.6197 --lonmin=13.9898 --latmax=50.3805 --lonmax=17.6958

No results.

But if I ask from 10th january to 11th january:

python peps_download.py -c S2 -a /home/atos/cron/peps.txt -w /home/atos/cron/downloads -d 2016-01-10 -f 2016-01-11 --latmin=48.6197 --lonmin=13.9898 --latmax=50.3805 --lonmax=17.6958

I get results, how is this possible? how may I know downloaded data date?

**Comment by olivierhagolle** [comment]
Hi Negroscuro,

When you provide a date YY-MM-DD, it is actually YY-MM-DD:00;00;00. So your two first request cannot provide any data, while the second one is gathering all data acquires on the 2016-01-10 .

I guess I should write that in the readme file, thanks for raising the question

Best regards,
Olivier

PS  It is nice to start "thanks for the useful tool", "please"...
Remember the service is provided on a voluntary basis by CNES for PEPS, and this tool, provided on a voluntary basis by myself, with no extra time allowed to it.

**Comment by negroscuro** [comment]
Sorry, indeed thank you for such useful tool :)
Understood, thank you for your explanation and for being so quick answering.
Cheers,
Mario.

**Comment by olivierhagolle** [comment]
:)

**Comment by negroscuro** [comment]
I tried:

sudo python peps_download.py -c S2 -a /home/atos/cron/peps.txt -w /home/atos/cron/downloads --start_date=2016-01-11:00;00;00 --end_date=2016-01-11:23;59;59 --latmin=48.6197 --lonmin=13.9898 --latmax=50.3805 --lonmax=17.6958
provide at least a point or rectangle
00: command not found
00: command not found
59: command not found
59: command not found

Something is not ok... any idea?
By the way python peps_download.py --help is also missing this date format, just in case you want to change it, at least for you to know if you did not already noticed.

Thank you.

**Comment by negroscuro** [comment]
I made it work with:
python peps_download.py -c S2 -a /home/atos/cron/peps.txt -w /home/atos/cron/downloads --start_date=2016-01-10T00:00:00 --end_date=2016-01-10T23:59:59 --latmin=48.6197 --lonmin=13.9898 --latmax=50.3805 --lonmax=17.6958

That is:
YYYY-MM-DDThh:mm:ss

Cheers,
Mario.

**Comment by olivierhagolle** [comment]
Oh, I did not know this worked ;)

But the following command would do excatly the same. That's what I meant, if you don't specify a time, T00:00:00 is added automatically.

python peps_download.py -c S2 -a /home/atos/cron/peps.txt -w /home/atos/cron/downloads --start_date=2016-01-10 --end_date=2016-01-11 --latmin=48.6197 --lonmin=13.9898 --latmax=50.3805 --lonmax=17.6958

**Comment by olivierhagolle** [comment]
And I added an example in the readme

**Comment by negroscuro** [comment]
Nice, thank you for your selfless work!
cheers.
