### ISSUE TITLE
weird problem on peps_download

### ISSUE THREAD

**Issue by negroscuro** [olivierhagolle/peps_download#7]
Hi,
I have been using for long time this nice tool, but not for some weeks and now I am back with it and now every time I run it:
python peps_download.py -c S2 -a /home/atos/cron/peps.txt -w /home/atos/cron/downloads -d 02/01/2016T00:00:00 -f 02/01/2016T23:59:59 --latmin=56.3814 --lonmin=22.1911 --latmax=57.0089 --lonmax=24.1131

I got:
Traceback (most recent call last):
  File "peps_download.py", line 136, in <module>
    for i in range(len(data["features"])):
KeyError: 'features'

I a do not know why...
Any idea?
thank you in advance.

**Comment by negroscuro** [comment]
Sorry i think it is my fault I did not realize I started using date format:
dd/mm/YYYY

**Comment by negroscuro** [comment]
Anyway, when I stop the process by CTRL+Z or CTRL+C... is there a good way to stop it? how should I do? because I found sometimes a python process still working in background downloading ZIP sentinel2 files.

**Comment by olivierhagolle** [comment]
Hi @negroscuro 
You're right, wrong date format.
When you do CTRL+Z, the module runs in background. You should use CTRL-C, but in python it is not always working at once. Don't ask me why...

Or you may use CTRL+Z and kill the process with kill %N, N being the number you get when pressing CTRL-Z

Best regards,
olivier
