### ISSUE TITLE
problem with peps_download tmp.tmp file not found

### ISSUE THREAD

**Issue by negroscuro** [olivierhagolle/peps_download#8]
Hello,
thank you for this nice tool, i have been using it for quite some time but today something weird happened.

I do:
python peps_download.py -c S2 -a /home/atos/cron/peps.txt -w /home/atos/cron/downloads -d 2016-01-13T00:00:00 -f 2016-01-13T23:59:59 --latmin=38.7060 --lonmin=30.8088 --latmax=40.7339 --lonmax=33.9015

But I got:
File "peps_download.py", line 168, in <module>
    with open(tmpfile) as f_tmp:
IOError: [Errno 2] No such file or directory: '/home/atos/cron/downloads/tmp.tmp'

I do not know hwat the problem is, my first thought was permissions but I gave full permisions to the folder and nothing changed.

any idea?

**Comment by negroscuro** [comment]
Now it is back working it seems was something remote related with PEPS servers.

**Comment by olivierhagolle** [comment]
Yes, PEPS has had some maintenance periods; Thanks for letting us know it is back to normal.
